### ISSUE TITLE
"Page's .Hugo is deprecated and will be removed in a future release."

### ISSUE THREAD

**Issue by rfilmyer** [bjacquemet/personal-web#1]
When building, I get this message:

    WARN 2019/05/15 16:41:47 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.

This appears to be coming from [here](https://github.com/bjacquemet/personal-web/blob/9d9842c2c3809cca04fd6fef14ebb4426e8761a2/layouts/partials/head/meta.html#L10), but possibly from other places.

**Comment by bjacquemet** [comment]
Hi @rfilmyer ,
thanks for pointing this out. I had an older version of Hugo installed.
I just changed 
```
{{ .Hugo.Generator }}
```
to 
```
{{ hugo.Generator }}
```
in `/layouts/partials/head/meta.html` which solves the issue. I didn't find any other issue when upgrading version.

Please let me know if you have any other issue. Hope you find the theme useful.
