### ISSUE TITLE
demo site lacking css

### ISSUE THREAD

**Issue by harrysarson** [bjacquemet/personal-web#13]
Hi, I noticed your demo site is looking slightly out of sorts:

![image](https://user-images.githubusercontent.com/16308754/83459753-eb4f2300-a45c-11ea-8406-2c0a23807406.png)

I think some of the css is not being loaded properly.

**Comment by bjacquemet** [comment]
Thanks for the heads up!
Actually, the problem was that Netlify moved all the sites without custom domain from `.com` to `.app` last month. 
I had not updated the baseURL in the config file. That's now done!
Thanks
