### ISSUE TITLE
Failed for the `master` branch as GitHub Pages because of YAML error

### ISSUE THREAD

**Issue by MikeRosTX** [bjacquemet/personal-web#14]
Git several different errors like the following picture, and the email I sent you:

![image](https://user-images.githubusercontent.com/11631454/84317754-f37d2180-ab32-11ea-8505-352be71107d3.png)

----- Forwarded Message -----
From: GitHub <support@github.com>
To: Mike Rosado 
Sent: Tuesday, June 9, 2020, 04:24:01 PM CDT
Subject: [MikeRosTX/personal-web] Page build failure

The page build failed for the `master` branch with the following error:

There was a **YAML syntax error on line 2 column 1 in `<unknown>`: `did not find expected key while parsing a block mapping`**. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-yaml-in-data-file.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=270923538&page_build_id=185180385

**RESOLUTION:** Found the answer **[here](https://stackoverflow.com/questions/54739382/hugo-fails-to-build-with-github-pages-because-of-yaml-error)** regarding adding a **.nojekyll** (empty file) to the root of my project, and pushing it to `master`. No more GitHub build errors.

**SUGGESTION/RECOMMENDATION:**
- Either add a **.nojekyll** file to your temple wherever you deem is the best place for it.\
- Or include a section in the **README.md** that mentions if they're using this Hugo template to create a GitHub Page, they should add a **.nojekyll** in the root folder of their project.

**Comment by bjacquemet** [comment]
Hi Mike, 
As mentioned in my email, the [the Hugo tutorial](https://gohugo.io/hosting-and-deployment/hosting-on-github/) should be more helpful
Cheers
