### ISSUE TITLE
Can't override sass styles

### ISSUE THREAD

**Issue by L4ZZA** [bjacquemet/personal-web#16]
I've been trying to fix some styling issues that come from the `themes/personal-web/assets/sass/custom.sass` by duplicating the it to my root folder and changing `$primary-color` variable does not have any effect.

Even moving all the assets content to my root dir and editing the files does not have any effetct.. do you have any idea on what is going on or if I'm doing anything wrong?

I even moved all the files from the assets folder to my root directory, but even if this time the website renders correctly none of the edits is applied even after restarting the local server.

```
Failed to render pages: render of "section" failed: execute of template failed: template: post/list.html:1:3: executing "post/list.html" at <partial "header" .>: error calling partial: execute of template failed: template: partials/header.html:3:4: executing "partials/header.html" at <partial "head/head" .>: error calling partial: execute of template failed: template: partials/head/head.html:5:5: executing "partials/head/head.html" at <partial "head/style" .>: error calling partial: "C:\dev\web\Hugo\lazza-portfolio\layouts\partials\head\style.html:4:59": execute of template failed: template: partials/head/style.html:4:59: executing "partials/head/style.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
```
![image](https://user-images.githubusercontent.com/17835185/89123536-09bab480-d4c8-11ea-9839-37d6214a0c4e.png)

**Comment by bjacquemet** [comment]
I guess that in order to modify the sass files, you'd have to duplicate the files and adapt the `head/style` file as well.
It seems that's were you have your issue.

Otherwise, you can add some styling with the customCSS file:
```
[params.assets]
  favicon = "/images/favicon.ico"
  customCSS = ""
```

**Comment by L4ZZA** [comment]
Adding a custom CSS works, but is tedious. I was looking for a way to change the $primary-color variable so that it would update all its instances.

**Comment by bjacquemet** [comment]
Hi  @L4ZZA 
I think you'll find your answer in this issue: #18 
Tell me if it solves your problem

**Comment by KevinCawley** [comment]
I also have this issue. In order to work around this I had to directly edit the SASS file inside of resources, which also required me to remove the integrity for it to work. From what I can read I need to download an extended version of hugo for these files to be read so I can change them in the css files without having to remove the integrity and edit this sass?

**Comment by bjacquemet** [comment]
@KevinCawley Did you try what I mention in #18 ?
> I've double checked the issue: you can override the _variables.sass by duplicating it from the theme folder to the assets/sass folder in your site root.

**Comment by KevinCawley** [comment]
I used hugo_extended in order to use that file.
