### ISSUE TITLE
Thumbnail and logo images don't display 

### ISSUE THREAD

**Issue by evahamburgcodingschool** [bjacquemet/personal-web#17]
Hi Baptiste,
Thank you for your nice theme. I have only two issues. 

1. The thumbnail images from each portfolio entry don't display on the portfolio overview page. The latest project doesn't show on home. The logo (my pic) from config.toml doesn't display.

2. designs, techs, projectUrl, jobDate and testimonial (commented out) don't appear on each portfolio. This was already missing from the sample project.

Here are my code and gh pages:
https://github.com/evahamburgcodingschool/portfolio
https://evahamburgcodingschool.github.io/portfolio/

Thanks in advance for your time and help
Eva

**Comment by evahamburgcodingschool** [comment]
Set it up all over again. That solved issue 2, but issue 1 persists. I might not have the right path to the images. What is odd is it worked nicely on my computer until I made the git commit and set up gh-pages. Now, it does not work locally any more either.

Here is the new code:
https://github.com/evahamburgcodingschool/portefeuille
https://evahamburgcodingschool.github.io/portefeuille/

TIA Eva

**Comment by bjacquemet** [comment]
Hi Eva, 
Sorry for the late response.
As indicated in the issue #14, you should have a look at [Hugo's documentation for hosting on Github pages](https://gohugo.io/hosting-and-deployment/hosting-on-github/) to implement your website on Github pages.
Cheers
Baptiste

**Comment by evahamburgcodingschool** [comment]
Hi Baptiste,
Thank you for taking the time to reply. I have followed the documentation to host the Github pages via the "Deployment of Project Pages From Your gh-pages branch" path. I made sure that I have the correct baseURL (<USERNAME>.github.io/<PROJECT>/). 

Nevertheless, the way the public folder is populated, <PROJECT> is missing in the image src's, e.g. it is
https://<USERNAME>.github.io/image-folder/image-name.jpg  
but it should be
https://<USERNAME>.github.io/<PROJECT>/image-folder/image-name.jpg

What's the best fix?

Cheers, Eva

**Comment by bjacquemet** [comment]
I guess this is a problem of deployment or settings in GH.
Sorry I can't further help as I'm using Netlify

**Comment by evahamburgcodingschool** [comment]
Thanks for your reply. It must have been a deployment error on GitHub Pages. I simply changed all src manually in the index.html files of the gh-pages branch. Not an elegant solution but it displays what needs to be displayed.
