### ISSUE TITLE
SASS _Variables file won't update

### ISSUE THREAD

**Issue by Ahmad-Khaled** [bjacquemet/personal-web#18]
Been trying to edit some of the colors from the _variables.sass file but it won't update in the website.

**Comment by bjacquemet** [comment]
Did you duplicate the file or modify the on in your `/themes` folder?
I don't think duplicating the file would work as it is built right now...

**Comment by bjacquemet** [comment]
Hi @Ahmad-Khaled 
I've double checked the issue: you can override the `_variables.sass` by duplicating it from the theme folder to the `assets/sass` folder in your site root.

Then, check what variables are actually used. For instance, the color of the links is the `$secondary-color`.

**Comment by mohyddintash** [comment]
@Ahmad-Khaled @bjacquemet I know this issue is closed, but in case anyone still has this issue, you need to make sure that you have hugo extended version installed on your machine for sass/css file to get parsed.
