### ISSUE TITLE
Original source of the svg icons

### ISSUE THREAD

**Issue by GrahamCampbell** [bjacquemet/personal-web#2]
Hi there. What was the original source of the svg icons please? Is there any scope for adding more? I'd quite like to link to GitLab as well as GitHub.

**Comment by GrahamCampbell** [comment]
Oh, I think I recognize the source? Font awesome?

**Comment by bjacquemet** [comment]
Indeed! I backed the project when they launched version 5, but didn't want to restrict to only FA icons

You have to add the path in `layouts/partials/svg.html`, but be careful with the viewBox. 

I have a Sketch file for that, I could add the other social accounts. What would be your need? I'm thinking Facebook, Gitlab, Instagram, Codepen, Youtube. Any other?

**Comment by bjacquemet** [comment]
Hi @GrahamCampbell 
I just added the social icons. It should give what you needed.
Cheers

**Comment by GrahamCampbell** [comment]
Great work. Could you add Keybase and ORCID too please?

**Comment by bjacquemet** [comment]
I can't find ORCID's icon.
I will add Keybase later today
Baptiste

**Comment by GrahamCampbell** [comment]
ORCID's icon is at https://orcid.org/trademark-and-id-display-guidelines. Note that they do not permit recolouring it. It must remain green.

**Comment by bjacquemet** [comment]
Hi Graham,
I recommend you add it into your bio (for example) then, as it's a pretty
specific case.
Cheers
