### ISSUE TITLE
Editing .css files breaks the layout completely

### ISSUE THREAD

**Issue by jsnetors** [bjacquemet/personal-web#20]
Title says it all. I tried to change a bit of the sidebar length and other small details but when I build the site again, it jumbles everything. It also happens with any modification of these files, even identation. I don't know if I'm missing something but looking at the available documentation, there was nothing to be found about this kind of modification. How can I fix this?

**Comment by bjacquemet** [comment]
Hi @jsnetors 
You should override the `_variables.sass` file to do so. You can do it by duplicating it from the theme folder to the assets/sass folder in your site root.

Then override the variable 
```
$sidebar-width: 30%
```
