### ISSUE TITLE
Show sidebar image on mobile

### ISSUE THREAD

**Issue by gabrc52** [bjacquemet/personal-web#21]
It'd be nice to be able to show the sidebar background image on mobile, since it just shows a gradient. 

I'd like to be able to customize the way the background from the top bar (like the sidebar on bigger screens) looks like, to either use the same image as on desktop or a different one.

**Comment by bjacquemet** [comment]
Hi @gabrc52 
you can do it.
- Duplicate your `scaffold.sass` into your root folder `/assets/sass`
- Modify the `+smartphone` version of header (line 159)

From 
`background: $dark-blue !important`
to:
```
background: inherit
background-size: cover
```
That should do the trick.
Cheers

**Comment by gabrc52** [comment]
Thanks! This works like a charm.
