### ISSUE TITLE
Is it possible to collapse/reduce the sidebar on mobile?

### ISSUE THREAD

**Issue by olamarre** [bjacquemet/personal-web#22]
Hi! Really like the theme :)

Is there any way to set a specific behavior for the sidebar on mobile when viewing one of the `content/post` or `content/portfolio` pages? For instance, I would like to collapse/reduce it (either to the side or top of the screen) to have more room for the actual posts instead of having to scroll past them when opening a new page. Thanks!

**Comment by bjacquemet** [comment]
Sorry @olamarre for the delay, didn't see the issue before

That's a good point. Do you mean having something like a hamburger menu at the top on mobile?
I'm gonna try to find some time to do it soon

**Comment by olamarre** [comment]
No worries! Yeah, I think something like a hamburger menu would be great. Thanks a lot!

**Comment by bjacquemet** [comment]
Hi @olamarre 
I've updated the theme yesterday, tell me what you think.
Cheers

**Comment by olamarre** [comment]
Awesome! I'll give it a try. Thanks a bunch :)
