### ISSUE TITLE
SVG Tag Icon

### ISSUE THREAD

**Issue by primercuervo** [bjacquemet/personal-web#3]
Hi! 

First of all, thanks for your work on this theme. I'm quite liking it! I gotta admit that I'm not proficient in webdev or similar, but your theme has been very helpful for getting me up to speed. Please bear with me if the question seems straight-forward, never worked on this before. 

I was trying to add taxonomies for tags and check how the theme works for blog posting, and notice that the taxonomy is not there by default and that there isn't an SVG for Tag. The first one is something that I have sorted out, but I'm struggling with the format of the `svg.html`.

So, I copied the `svg.html` into my local layouts, as recommended by hugo's doc. And went to add a tag icon from the Font Awesome info webpage, where it is only said that I need to add `<i class="fas fa-tag"></i>`, which doesn't seem nearly close that what we can see [in any icon description](https://github.com/bjacquemet/personal-web/blob/master/layouts/partials/svg.html#L4). 

Could you please give me a hint about what these `paths` actually mean, and/or how should I add the tag icon? Is there a better way to extend this `svg.html` apart from copy/paste the whole file and work over it?

Thanks in advance!

**Comment by primercuervo** [comment]
Okay, after a good sesh of RTFM, I'm realizing that my question was probably too broad, and most of it is not directly related to the theme. Sorry about that!

I got hands-on and figured out most of my concerns. Understood the paths, and the viewBox. Still failed miserably to devise an straightforward workflow from downloading  the SVG from the Font-awesome website (which seems to default size to 512pt) to pasting it into the partial svg.html with the correct size. I had to resize it using external tools. Is that the workflow you follow?

I'll change the issue to "request for Tag Icon", as it seems to me that it would be cool to have it out of the box, but would like your insights on how to do this more effectively. Probably the way I'm following is the actual way to go. 

I'm also still wondering if there is a better way to extend the svg partial rather than copying to whole file to the local portion of the files

**Comment by bjacquemet** [comment]
Hi @primercuervo,

There are two different things here:
- I don't use FA in this repository, so unless you add the script to your project, you won't be able to use the FA icons.
- You can override the theme `svg.html` file by duplicating and modifying the file in your root directory (i.e: copy `themes/personal-web/layouts/partials/svg.html` into `layouts/partials/svg.html`) and then modify this new file. It works for every file in the `themes/personal-web` folder. See https://orcid.org/trademark-and-id-display-guidelines

As for your second question, yes, I use a Sketch file to create the icons and optimize them with `svgo`. I'm adding the file in the repo with further instructions right now.

If you need a specific icon that could be useful for the community, let me know.

**Comment by bjacquemet** [comment]
Hi @primercuervo 
In the last [commit](https://github.com/bjacquemet/personal-web/commit/bf81b17cf3ec00bbb275ca6c8a102afb8c9e2c96) I added the tag svg.
Let me know if it solves your problem

**Comment by primercuervo** [comment]
Hi @bjacquemet,

yes, I can see and use the tag icon. Thanks!
