### ISSUE TITLE
About Page Doesn't work from exampleSite

### ISSUE THREAD

**Issue by MaxProfit** [bjacquemet/personal-web#9]
It looks like the way exampleSite's directory is structured that the about page doesn't show up properly. I've fixed this by just adding an about directory under content, then moving about.md in there and changing it's name to _index.md

**Comment by MaxProfit** [comment]
https://github.com/bjacquemet/personal-web/pull/10

**Comment by bjacquemet** [comment]
Thanks, indeed it wasn't working properly. Not sure if it isn't working since the Hugo version update or if it was like that before. Now it's showing properly. Thanks!
